# Generated by Django 3.0.5 on 2020-04-28 19:15

from django.db import migrations
from django.contrib.auth.models import User


def add_user(apps, schema_editor):
    user = User.objects.create_user('ucenik.1@gmail.com', 'ucenik.1@gmail.com', '12345')
    user.first_name = 'Učenik'
    user.last_name = 'Učeniković'
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perftest1', '0002_auto_20200428_1438'),
    ]

    operations = [
        migrations.RunPython(add_user),
    ]
